### ISSUE TITLE
Cannot download hmr2_data.tar.gz

### ISSUE THREAD

**Issue by zhixionl** [shubham-goel/4D-Humans#18] opened 2023-07-07 21:53 UTC
For some reasons I could not download data from https://people.eecs.berkeley.edu/~shubham-goel/projects/4DHumans/hmr2_data.tar.gz and it shows 404 file not found.

**Comment by shubham-goel** [comment] 2023-07-08 07:10
Hi @zhixionl, we're aware of this issue, caused by the server going offline. We're working on fixing this ASAP.

THank you for your patience.

**Comment by shubham-goel** [comment] 2023-07-10 01:50
This, this problem should have been fixed now. Thanks!

**Closed by shubham-goel** 2023-07-10 01:50 UTC
